server:
  port: 8082

spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schema: classpath:schema_pg.sql
    data: classpath:data_pg.sql
    initialization-mode: always

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,logfile
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    diskspace:
      enabled: false
logging:
  file:
    name: stdout.log