DROP TABLE IF EXISTS AUTHORS;

CREATE TABLE AUTHORS (
    AUTHOR_ID INT PRIMARY KEY,
    AUTHOR_NAME VARCHAR(2048)
);

DROP TABLE IF EXISTS GENRES;

CREATE TABLE GENRES (
    GENRE_ID INT PRIMARY KEY,
    GENRE_NAME VARCHAR(2048)
);

DROP TABLE IF EXISTS BOOKS;

CREATE TABLE BOOKS (
    BOOK_ID INT PRIMARY KEY,
    BOOK_NAME VARCHAR(2048),
    AUTHOR_ID INT,
    GENRE_ID INT
);

DROP TABLE IF EXISTS COMMENTS;

CREATE TABLE COMMENTS (
    COMMENT_ID INT PRIMARY KEY,
    BOOK_ID INT,
    TEXT VARCHAR(2048)
);

ALTER TABLE BOOKS ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID);

ALTER TABLE BOOKS ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRES(GENRE_ID);

ALTER TABLE COMMENTS ADD FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID) on delete cascade;