DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;

CREATE TABLE AUTHORS (
    AUTHOR_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUTHOR_NAME VARCHAR(2048)
);

CREATE TABLE GENRES (
    GENRE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    GENRE_NAME VARCHAR(2048)
);

CREATE TABLE BOOKS (
    BOOK_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BOOK_NAME VARCHAR(2048),
    AUTHOR_ID BIGINT,
    GENRE_ID BIGINT
);

CREATE TABLE COMMENTS (
    COMMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BOOK_ID BIGINT,
    TEXT VARCHAR(2048)
);

ALTER TABLE BOOKS ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID);

ALTER TABLE BOOKS ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRES(GENRE_ID);

ALTER TABLE COMMENTS ADD FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID) on delete cascade;